# Generated by Django 3.1.4 on 2021-01-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=80, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('ano', models.IntegerField(null=True)),
                ('valor', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('ENROLLMENT FEE', 'ENROLLMENT FEE'), ('MONTHLY PAYMENT', 'MONTHLY PAYMENT')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('GENERATE', 'GENERATE'), ('REQUESTED', 'REQUESTED'), ('PAID', 'PAID')], max_length=15, null=True)),
            ],
        ),
    ]
