# Generated by Django 3.1.4 on 2021-01-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0004_auto_20210112_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ano',
            new_name='year',
        ),
    ]
