# Generated by Django 3.1.4 on 2021-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0005_auto_20210112_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='enrollment',
            field=models.CharField(default='NOT PAID', max_length=15, null=True),
        ),
    ]
