# Generated by Django 3.1.4 on 2021-01-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0006_userprofileinfo_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='enrollment',
        ),
    ]
