# Generated by Django 3.1.4 on 2021-01-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0009_auto_20210117_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='date_audit',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
