# Generated by Django 3.1.4 on 2021-01-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0010_auto_20210117_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
    ]
