# Generated by Django 3.1.4 on 2021-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0011_auto_20210117_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jump',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pilates',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pilates',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spin',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
    ]
