# Generated by Django 3.1.4 on 2021-01-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0012_auto_20210117_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
    ]
