# Generated by Django 3.1.4 on 2021-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0013_auto_20210117_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='date_audit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='hour_audit',
            field=models.TimeField(null=True),
        ),
    ]
