# Generated by Django 3.1.4 on 2021-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0015_auto_20210118_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('ENROLMENT FEE', 'ENROLMENT FEE'), ('MONTHLY PAYMENT', 'MONTHLY PAYMENT')], max_length=30, null=True),
        ),
    ]
