# Generated by Django 3.1.4 on 2021-01-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0016_auto_20210123_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='prefix',
            field=models.CharField(choices=[('+353', '+353'), ('+44', '+44'), ('+39', '+44'), ('+33', '+44'), ('+351', '+44'), ('+34', '+44')], max_length=4, null=True),
        ),
    ]
