# Generated by Django 3.1.4 on 2021-01-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccfit_app', '0017_auto_20210123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='prefix',
            field=models.CharField(choices=[('+353', '+353'), ('+44', '+44'), ('+39', '+39'), ('+33', '+33'), ('+351', '+351'), ('+34', '+34')], max_length=4, null=True),
        ),
    ]
